language: java
notifications:
  slack:
    secure: os7oCGhhlkHH6df4sCLiMrdS78BjbGbhAg6q+3tGhzsLGz7spc2ZOQLG1seszLmxqCgJTowIo/JpDT9AKRFh9e+MnhbEMFO5foa6OPK+n9D+KkL9IaimW4uNRFS7HVD2ZcRdH7zw6oc0ErylWF1gFefsC4iwoFiWfmOUw5jEqEciWfAx8i05gA9dcQMtrUnJ2RUP4h3TzlRTnZT0bzdjVsr02LVwGbG8WMxUwURWhvNxkQD+IqL+VLDNaw/EontkRaD2E8k2Ro6f51o2VbBM153nA0pWxW0T9fQ277E3bQDTM/UiAvdeKWfVCPtosQF2mnm+nIAxM+gBv+sb74xn39KxmMlYaGorUUsOKxmlsZuTdfGcC2E5fDnNl/RUqWNLxTBmFHK31QJ/mAjltOa3EocMOo3ISYfYtY4NLJNKc8oZaF0Pe3FSc5dz505+o75xgJ/X8GTHE8DCuQtEUFNZ9VpG7IH/KGr3LQAkjQjKJPaMVWkuup+t5Yw75rIG/WI3QNdZ4A5YM5Ex9YRXkql/2kdFZwzfj76MM0BeL3ty/BlDsCdCg69vXiIztAj7+ZRwH+MV0TjwBg+X9cSoUi1hlsEzfWRChHZ0eSLsh6U469NaSB+zttVC6BTSXNf/sO/UFAFnVbdhwiyv6rYjBnssRdSeQvAlQvcHgnAoCy0X+Dc=
deploy:
  provider: releases
  api_key:
    secure: PxZVRum5+AruxU8f0YfLOnRlLG0uraURUCTGQn4+0oD3NNrr85ctLVPGYoCaL6+6CUiBFUkPJcQ2pPdETntjRaR02b+6+DudHCgKnu7sGOcmcKKuuMUZnR+psT6w0x56eKy66ScCOHvIDhpDVXidIhI8tijCxMGbLvcC5Ss2JAcoSZ8RnbEvN4g9F1kcKfTAOy2N/1Ov28QyR7B8dWU33+GRwQtMUhIADTryk3sArcOsrwF4WVvL951QLyaS1JhNpyJshHbIwFRKhfqVHu8pB623AgnbpzXIOq4kDkChAnnVzvjzLBZWoaUS+NxKPFaOT+s13DSpD/qHG+gPU1YNheD4q8bem9qdG3uV6idFaFLfz6kWce5SjJ7HB9yuQpIGqy8AaRBTL/TfpUzZ+5Ml0bn8aV0lg8Y2sUAx9QXFlY8AAG43qltwPHpmj1UIQDTv2I3RdPTmJc791x/4TlIRXfpXFAIqnpCP5MtZlhigHn53cjvhfXne1hrkkOJg3YqrteDA7fEeNii7AkLwusKRqL70ib/Sp7ipe4hARzUYzGABtWezIFepFma2eDam5CDBOU5MZgCHZwzoeeC9IMN4Faj4sa8AK8knn3bwS5B6N/30JlXaH8ubNdGqKGuzemLRYhxORvUVwdjZ59WNEDVmS1+QfhI+ywe9ZZNcDrUerd8=
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-confluence-plugin